name: Generate and publish report

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - "**/*.md"
  schedule:
    # Runs every day at 3am
    - cron: "0 3 * * *"

permissions:
  pages: write
  id-token: write

jobs:
  build:
    name: Build Report
    runs-on: ubuntu-22.04
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Use Node.js 24.x
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: 24.x

      - name: Install and Build
        run: |
          npm ci
          npm run build

      - name: Generate Report
        run: |
          npm run generate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: ./out

  deploy:
    name: Deploy Report to GitHub Pages
    runs-on: ubuntu-22.04
    needs: build
    environment: github-pages
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
